### ISSUE TITLE
How to get this plugin work well?

### ISSUE THREAD

**Issue by krisfans** [Freed-Wu/Leaderf-keymaps#1]
Thanks for your work. I can't get list of keymaps after I type `:Leaderf keymaps`?
![图片](https://user-images.githubusercontent.com/57793534/153375341-bb17e4ef-b61a-4d4d-9c33-08f3c73a5278.png)

**Comment by Freed-Wu** [comment]
This plugin's usage is:

1.  `:Leaderf kemaps`
2. select the keymap you want
3. press `<CR>`, it will execute `set keymap=` the keymap you want.

In <https://github.com/Freed-Wu/LeaderF-keymaps/blob/master/autoload/leaderf/keymaps.vim#L10>

```vim
execute 'set keymap=' . a:line
```
